[package]
name = "montecarlo-pi"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
num_cpus = "1.17.0"
rand = "0.9.2"
rayon = "1.11.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
